2025-02-25 17:29:27.762466: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1740522567.783095 4051083 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1740522567.789809 4051083 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-25 17:29:27.813706: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 142, in _path_stat
FileNotFoundError: [Errno 2] No such file or directory: '/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/lib/io/__init__.cpython-39-x86_64-linux-gnu.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/gpfs_common/share01/csc591s25/kpatel48/GenAI-for-Systems-Gym/homework-1/models/MLP/cache_replacement/policy_learning/cache_model/main.py", line 41, in <module>
    import tensorflow.compat.v1 as tf
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/__init__.py", line 49, in <module>
    from tensorflow._api.v2 import __internal__
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/__init__.py", line 11, in <module>
    from tensorflow._api.v2.__internal__ import distribute
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/distribute/__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__.distribute import combinations
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/_api/v2/__internal__/distribute/combinations/__init__.py", line 8, in <module>
    from tensorflow.python.distribute.combinations import env # line: 456
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/distribute/combinations.py", line 33, in <module>
    from tensorflow.python.distribute import collective_all_reduce_strategy
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 25, in <module>
    from tensorflow.python.distribute import cross_device_ops as cross_device_ops_lib
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/distribute/cross_device_ops.py", line 28, in <module>
    from tensorflow.python.distribute import cross_device_utils
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/distribute/cross_device_utils.py", line 22, in <module>
    from tensorflow.python.distribute import values as value_lib
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/distribute/values.py", line 23, in <module>
    from tensorflow.python.distribute import distribute_lib
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/distribute/distribute_lib.py", line 205, in <module>
    from tensorflow.python.data.ops import dataset_ops
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/data/__init__.py", line 21, in <module>
    from tensorflow.python.data import experimental
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/data/experimental/__init__.py", line 99, in <module>
    from tensorflow.python.data.experimental import service
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 419, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 23, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 16, in <module>
    from tensorflow.python.data.util import structure
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/data/util/structure.py", line 32, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/ops/ragged/__init__.py", line 28, in <module>
    from tensorflow.python.ops.ragged import ragged_tensor
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/ops/ragged/ragged_tensor.py", line 3149, in <module>
    from tensorflow.python.ops.ragged import ragged_ops  # pylint: disable=unused-import, g-bad-import-order, g-import-not-at-top
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/ops/ragged/ragged_ops.py", line 27, in <module>
    from tensorflow.python.ops.ragged import ragged_array_ops
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/ops/ragged/ragged_array_ops.py", line 30, in <module>
    from tensorflow.python.ops import data_flow_ops
  File "/share/csc591s25/conda_env/new_env/lib/python3.9/site-packages/tensorflow/python/ops/data_flow_ops.py", line 28, in <module>
    from tensorflow.python.lib.io import python_io
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1395, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1541, in find_spec
  File "<frozen importlib._bootstrap_external>", line 156, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
KeyboardInterrupt
